version: "3.8"

services:
  nginx:
    image: nginx
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "1001:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - laravel-php
    networks:
      - laravel-networks

  laravel-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-php
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-networks

  laravel-db:
    image: mysql
    container_name: laravel-db
    restart: unless-stopped
    tty: true
    ports:
      - "1306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: laravel-db
      SERVICE_TAGS: dev
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/my.conf
    networks:
      - laravel-networks

  phpmyadmin:
    image: phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: laravel-db
      PMA_PORT: 3306
    networks:
      - laravel-networks

networks:
  laravel-networks:
    driver: bridge

volumes:
  db:
    driver: local
